# Generated by Django 4.1.3 on 2022-11-30 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2)),
                ('start_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('born_date', models.DateField()),
                ('salary', models.FloatField(default=0.0)),
                ('rating', models.FloatField(default=0.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('born_date', models.DateField()),
                ('grade_lab', models.FloatField(default=0.0)),
                ('grade_exam', models.FloatField(default=0.0)),
                ('grade_final', models.FloatField(default=0.0)),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.classroom')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
