# Generated by Django 4.1.3 on 2022-12-01 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_book_alter_studentproxy_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='books',
        ),
    ]
