# Generated by Django 4.1.3 on 2022-12-01 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_alter_book_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookID',
            field=models.IntegerField(default=0),
        ),
    ]
