# Generated by Django 4.1.3 on 2022-12-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_remove_book_bookid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
